services:

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_URL=${MONGO_URL}
      - TTL=${TTL}
      - SESSION_RECOVERY_PERIOD=${SESSION_RECOVERY_PERIOD}
      - LEADERBOARD_MAX=${LEADERBOARD_MAX}
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --quiet
      interval: 10s
      timeout: 20s
      start_period: 30s
      retries: 5
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
  mongodb_config: